### ISSUE TITLE
equal( com.parent_permlink, o.parent_permlink ): The permlink of a comment cannot change.

### ISSUE THREAD

**Issue by diegopucci** [steemit/sc2-sdk#25]
Keep getting this error when updating a post, even though the permlink has not been changed. What's wrong?

**Comment by diegopucci** [comment]
Sorry was my mistake

**Comment by ogbiyoyosky** [comment]
Would to know how you edit a post because am getting the same error

**Comment by tharey** [comment]
Well, I am also getting the same error when trying to update posts. Can someone please explain this to me?
