### ISSUE TITLE
Not working properly with Nodejs

### ISSUE THREAD

**Issue by liyihe96** [steemit/sc2-sdk#28]
It works fine on browser but when running this sdk on nodejs, the requests always fail with this error.

{ SDKError: sc2-sdk error
  name: 'SDKError',
  error: [Function],
  error_description: undefined }

I checked the access token is set correctly. I believe the fault is how isomorphic-fetch behaves differently on nodejs.

**Comment by liyihe96** [comment]
I created a repo using axios instead of isomorphic-fetch following the same pattern and works fine on nodejs. Also with axios it uses Promise instead of callbacks, so code could be cleaner. This could make other dapp developers' life easier. Do you accept a pull request or should I create a new package instead?

**Comment by gregory-latinier** [comment]
Can you provide some code to reproduce the issue ?
